### ISSUE TITLE
TG通知不能用

### ISSUE THREAD

**Issue by 794329041** [RikudouPatrickstar/jd-base#21]
TG_BOT_TOKEN和TG_USER_ID没有问题 别的镜像可以用 大佬的这个就不行
telegram发送通知消息失败！！

RequestError: connect ECONNREFUSED 149.154.167.220:443
    at ClientRequest.<anonymous> (/jd/scripts/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/jd/scripts/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1615378786972,
    socket: 1615378786974,
    lookup: 1615378787066,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1615378787084,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 92,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 112
    }
  }
}

**Comment by RikudouPatrickstar** [comment]
奇怪了，这报错也是 lxk0301 的脚本报的错啊，我重新生成下 docker 镜像，你10分钟之后重新拉取镜像试试

**Comment by 794329041** [comment]
好的 大佬

**Comment by RikudouPatrickstar** [comment]
刚刚测试了下是有效的啊，你是不是这会网络出了什么问题

**Comment by 794329041** [comment]
恩 是我的原因 换个节点好了 感谢大佬
